# -----------------------------------------------------------------------------
# csb-hcs-gaussdb — provision
# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that
# file and run `make gen-config` instead of editing this one.
# Run:  cd terraform/gaussdb/provision
#       tofu init
#       tofu plan  -var-file=../../examples/shared.tfvars -var-file=../../examples/gaussdb/provision.tfvars
#       tofu apply -var-file=../../examples/shared.tfvars -var-file=../../examples/gaussdb/provision.tfvars
# Auth: export HCS_ACCESS_KEY=... HCS_SECRET_KEY=...   (or IAM user/password)
#       export HCS_INSECURE=true                        (self-signed certs)
# -----------------------------------------------------------------------------

# --- network (region/cloud/vpc_name come from examples/shared.tfvars) ---
subnet_name = "subnet-gaussdb"

# --- sizing ---
flavor = "gaussdb.opengauss.ee.dn.m6.2xlarge.8.in"
volume_type = "ULTRAHIGH"
volume_size = 480

# --- instance ---
instance_name = "csb-test-gaussdb"
ha_mode = "combined"
ha_consistency = "eventual"
ha_consistency_protocol = "quorum"
sharding_num = 3
coordinator_num = 3
backup_start_time = "03:00-04:00"
backup_keep_days = 7
solution = "hcs1"  # AZ count depends on the solution
availability_zones = ["az1", "az2", "az3"]  # two entries for .ha flavors / must match the solution
port = "8000"

# security_group_name   = "sg-gaussdb"           # optional; required for custom ports
# password              = "..."                  # optional; random when omitted

# --- tags ---
labels = {}
# namespace / instance_name / created_by tags come from the broker when it runs this module
