# -----------------------------------------------------------------------------
# csb-hcs-rds-postgresql — provision
# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that
# file and run `make gen-config` instead of editing this one.
# Run:  cd terraform/rds-postgresql/provision
#       tofu init
#       tofu plan  -var-file=../../examples/shared.tfvars -var-file=../../examples/rds-postgresql/provision.tfvars
#       tofu apply -var-file=../../examples/shared.tfvars -var-file=../../examples/rds-postgresql/provision.tfvars
# Auth: export HCS_ACCESS_KEY=... HCS_SECRET_KEY=...   (or IAM user/password)
#       export HCS_INSECURE=true                        (self-signed certs)
# -----------------------------------------------------------------------------

# --- network (region/cloud/vpc_name come from examples/shared.tfvars) ---
subnet_name = "subnet-rds-pg"
security_group_name = "sg-rds-pg"

# --- sizing ---
flavor = "rds.pg.n1.large.2"  # single node; use *.ha flavors with two AZs

# --- instance ---
instance_name = "csb-test-rds-pg"
ha_replication_mode = "async"
backup_start_time = "03:00-04:00"
backup_keep_days = 7
pg_version = "12"
storage_gb = 100
volume_type = "ULTRAHIGH"
availability_zones = ["az1"]  # two entries for .ha flavors / must match the solution
port = 5432

# admin_password  = "..."                         # optional; random when omitted
# ha_replication_mode = "async"                  # used by .ha flavors only

# --- tags ---
labels = {}
# namespace / instance_name / created_by tags come from the broker when it runs this module
