# -----------------------------------------------------------------------------
# csb-hcs-elb — provision
# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that
# file and run `make gen-config` instead of editing this one.
# Run:  cd terraform/elb/provision
#       tofu init
#       tofu plan  -var-file=../../examples/shared.tfvars -var-file=../../examples/elb/provision.tfvars
#       tofu apply -var-file=../../examples/shared.tfvars -var-file=../../examples/elb/provision.tfvars
# Auth: export HCS_ACCESS_KEY=... HCS_SECRET_KEY=...   (or IAM user/password)
#       export HCS_INSECURE=true                        (self-signed certs)
# -----------------------------------------------------------------------------

# --- network (region/cloud/vpc_name come from examples/shared.tfvars) ---
subnet_name = "subnet-elb"

# --- sizing (ELB flavor IDs are site-created; from your broker plan config) ---
l4_flavor_id = "CHANGE_ME_L4"
l7_flavor_id = "CHANGE_ME_L7"

# --- instance ---
loadbalancer_name = "csb-test-elb"
listener_protocol = "TCP"
listener_port = 80
lb_method = "ROUND_ROBIN"
allocate_eip = false
eip_iptype = "5_bgp"
bandwidth_size = 5

# ipv4_address    = "192.168.1.100"              # optional; set to know the private VIP
# backend_members = [                             # optional; or register backends on bind
#   { address = "192.168.1.10", port = 8080 },
# ]

# --- tags ---
labels = {}
# namespace / instance_name / created_by tags come from the broker when it runs this module
