# -----------------------------------------------------------------------------
# csb-hcs-ecs — provision
# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that
# file and run `make gen-config` instead of editing this one.
# Run:  cd terraform/ecs/provision
#       tofu init
#       tofu plan  -var-file=../../examples/shared.tfvars -var-file=../../examples/ecs/provision.tfvars
#       tofu apply -var-file=../../examples/shared.tfvars -var-file=../../examples/ecs/provision.tfvars
# Auth: export HCS_ACCESS_KEY=... HCS_SECRET_KEY=...   (or IAM user/password)
#       export HCS_INSECURE=true                        (self-signed certs)
# -----------------------------------------------------------------------------

# --- network (region/cloud/vpc_name come from examples/shared.tfvars) ---
subnet_name = "subnet-ecs"
security_group_name = "sg-ecs"

# --- sizing ---
flavor = "s6.large.2"  # plan flavor; drop this line to auto-resolve from cores/memory

# --- instance ---
instance_name = "csb-test-ecs"
image_name = "Ubuntu 22.04 server 64bit"  # site-specific IMS image name
availability_zone = "az1"
system_disk_type = "business_type_01"  # site-specific disk type
system_disk_size = 40
allocate_eip = false
eip_iptype = "5_bgp"
bandwidth_size = 5

# admin_pass     = "..."                          # optional; random when omitted

# --- tags ---
labels = {}
# namespace / instance_name / created_by tags come from the broker when it runs this module
