# -----------------------------------------------------------------------------
# csb-hcs-dcs — provision
# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that
# file and run `make gen-config` instead of editing this one.
# Run:  cd terraform/dcs/provision
#       tofu init
#       tofu plan  -var-file=../../examples/shared.tfvars -var-file=../../examples/dcs/provision.tfvars
#       tofu apply -var-file=../../examples/shared.tfvars -var-file=../../examples/dcs/provision.tfvars
# Auth: export HCS_ACCESS_KEY=... HCS_SECRET_KEY=...   (or IAM user/password)
#       export HCS_INSECURE=true                        (self-signed certs)
# -----------------------------------------------------------------------------

# --- network (region/cloud/vpc_name come from examples/shared.tfvars) ---
subnet_name = "subnet-dcs"

# --- sizing ---
capacity = 0.125
cache_mode = "single"  # single | ha | cluster | proxy
engine_version = "5.0"

# --- instance ---
instance_name = "csb-test-dcs"
availability_zone = "az1"
port = 6379

# standby_availability_zone = "az2"              # required for ha mode
# password       = "..."                          # optional; random when omitted

# --- tags ---
labels = {}
# namespace / instance_name / created_by tags come from the broker when it runs this module
