# -----------------------------------------------------------------------------
# csb-hcs-obs — provision
# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that
# file and run `make gen-config` instead of editing this one.
# Run:  cd terraform/obs/provision
#       tofu init
#       tofu plan  -var-file=../../examples/shared.tfvars -var-file=../../examples/obs/provision.tfvars
#       tofu apply -var-file=../../examples/shared.tfvars -var-file=../../examples/obs/provision.tfvars
# Auth: export HCS_ACCESS_KEY=... HCS_SECRET_KEY=...   (or IAM user/password)
#       export HCS_INSECURE=true                        (self-signed certs)
# -----------------------------------------------------------------------------

# --- bucket ---
bucket_name = "csb-test-bucket-CHANGE_ME"  # globally unique in OBS, DNS-compatible
acl = "private"
storage_class = "STANDARD"
force_destroy = true  # convenient for trials; false in production

# --- instance ---
versioning = false

# versioning    = false
# encryption   = true                            # optional SSE-KMS

# --- tags ---
labels = {}
# namespace / instance_name / created_by tags come from the broker when it runs this module
