# -----------------------------------------------------------------------------
# Shared values for every module — GENERATED by scripts/gen-config.py from
# config/site-values.yaml; edit that file and run `make gen-config`.
# Pass it FIRST so per-module files can override:
#   tofu apply -var-file=examples/shared.tfvars -var-file=examples/<svc>/<mod>.tfvars
# -----------------------------------------------------------------------------

# --- connection ---
region = "cn-north-1"
cloud = "hcs.example.com"

# --- shared network ---
vpc_name = "vpc-default"
