#!/usr/bin/env python3
"""Generate the broker config and the example tfvars from config/site-values.yaml.

Single source of truth: config/site-values.yaml.
Outputs:
  hcs-broker.yaml                       (csb serve --config hcs-broker.yaml)
  examples/<service>/provision.tfvars   (direct OpenTofu runs)
"""
import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
VALUES_FILE = ROOT / "config" / "site-values.yaml"
BROKER_CONFIG = ROOT / "hcs-broker.yaml"

SERVICES = ["ecs", "rds-postgresql", "dcs", "elb", "gaussdb", "csms", "obs"]

# Per-service convention values that rarely change per site; emitted into the
# instance section so every required variable is covered.
CONVENTION_DEFAULTS = {
    "ecs": {"instance_name": "csb-test-ecs"},
    "rds-postgresql": {
        "instance_name": "csb-test-rds-pg",
        "ha_replication_mode": "async",
        "backup_start_time": "03:00-04:00",
        "backup_keep_days": 7,
    },
    "dcs": {"instance_name": "csb-test-dcs"},
    "elb": {"loadbalancer_name": "csb-test-elb"},
    "gaussdb": {
        "instance_name": "csb-test-gaussdb",
        "ha_mode": "combined",
        "ha_consistency": "eventual",
        "ha_consistency_protocol": "quorum",
        "sharding_num": 3,
        "coordinator_num": 3,
        "backup_start_time": "03:00-04:00",
        "backup_keep_days": 7,
    },
    "csms": {},
    "obs": {"versioning": False},
}


def tf(v):
    """Render a python value as an HCL literal."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return "[" + ", ".join(tf(i) for i in v) + "]"
    return json.dumps(str(v))


def kv(key, value, comment=None):
    line = f"{key} = {tf(value)}"
    if comment:
        line += f"  # {comment}"
    return line


HEADER = """# -----------------------------------------------------------------------------
# {title}
# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that
# file and run `make gen-config` instead of editing this one.
# Run:  cd terraform/{svc}/{mod}
#       tofu init
#       tofu plan  -var-file=../../examples/shared.tfvars -var-file=../../examples/{svc}/{mod}.tfvars
#       tofu apply -var-file=../../examples/shared.tfvars -var-file=../../examples/{svc}/{mod}.tfvars
# Auth: export HCS_ACCESS_KEY=... HCS_SECRET_KEY=...   (or IAM user/password)
#       export HCS_INSECURE=true                        (self-signed certs)
# -----------------------------------------------------------------------------
"""


def gen_provision_tfvars(v, svc):
    conn, net, inst = v["connection"], v["network"], v["instances"][svc]
    lines = [HEADER.format(title=f"csb-hcs-{svc} — provision", svc=svc, mod="provision")]

    if svc in net or svc.replace("-", "_") in net:
        entry = net.get(svc) or net.get(svc.replace("-", "_"))
        lines.append("# --- network (region/cloud/vpc_name come from examples/shared.tfvars) ---")
        lines.append(kv("subnet_name", entry["subnet_name"]))
        if "security_group_name" in entry:
            lines.append(kv("security_group_name", entry["security_group_name"]))
        lines.append("")

    svc_blocks = {
        "ecs": [
            "# --- sizing ---",
            ("flavor", "plan flavor; drop this line to auto-resolve from cores/memory"),
        ],
        "rds-postgresql": [
            "# --- sizing ---",
            ("flavor", "single node; use *.ha flavors with two AZs"),
        ],
        "dcs": [
            "# --- sizing ---",
            ("capacity", None),
            ("cache_mode", "single | ha | cluster | proxy"),
            ("engine_version", None),
        ],
        "elb": [
            "# --- sizing (ELB flavor IDs are site-created; from your broker plan config) ---",
            ("l4_flavor_id", None),
            ("l7_flavor_id", None),
        ],
        "gaussdb": [
            "# --- sizing ---",
            ("flavor", None),
            ("volume_type", None),
            ("volume_size", None),
        ],
        "csms": [
            "# --- secret ---",
            ("secret_name", None),
        ],
        "obs": [
            "# --- bucket ---",
            ("bucket_name", "globally unique in OBS, DNS-compatible"),
            ("acl", None),
            ("storage_class", None),
            ("force_destroy", "convenient for trials; false in production"),
        ],
    }

    optional_notes = {
        "ecs": [
            '# admin_pass     = "..."                          # optional; random when omitted',
        ],
        "rds-postgresql": [
            '# admin_password  = "..."                         # optional; random when omitted',
            "# ha_replication_mode = \"async\"                  # used by .ha flavors only",
        ],
        "dcs": [
            '# standby_availability_zone = "az2"              # required for ha mode',
            '# password       = "..."                          # optional; random when omitted',
        ],
        "elb": [
            '# ipv4_address    = "192.168.1.100"              # optional; set to know the private VIP',
            "# backend_members = [                             # optional; or register backends on bind",
            "#   { address = \"192.168.1.10\", port = 8080 },",
            "# ]",
        ],
        "gaussdb": [
            '# security_group_name   = "sg-gaussdb"           # optional; required for custom ports',
            '# password              = "..."                  # optional; random when omitted',
        ],
        "csms": [
            '# secret_text = "..."                            # optional; random when omitted',
            '# kms_key_id  = "..."                            # optional; default KMS key when omitted',
        ],
        "obs": [
            "# versioning    = false",
            '# encryption   = true                            # optional SSE-KMS',
        ],
    }

    block = svc_blocks[svc]
    lines.append(block[0])
    for item in block[1:]:
        key, comment = item
        value = v["elb_plan"][key] if svc == "elb" else inst[key]
        lines.append(kv(key, value, comment))
    lines.append("")

    lines.append("# --- instance ---")
    sizing_keys = {k for b in block[1:] for k in [b[0]]}
    merged = {**CONVENTION_DEFAULTS[svc], **inst}
    for key, value in merged.items():
        if key in sizing_keys:
            continue
        comment = {
            "image_name": "site-specific IMS image name",
            "system_disk_type": "site-specific disk type",
            "availability_zones": "two entries for .ha flavors / must match the solution",
            "solution": "AZ count depends on the solution",
            "port": None,
        }.get(key)
        lines.append(kv(key, value, comment))
    lines.append("")

    lines.extend(optional_notes[svc])
    if optional_notes[svc]:
        lines.append("")

    lines.append("# --- tags ---")
    lines.append("labels = {}")
    lines.append("# namespace / instance_name / created_by tags come from the broker when it runs this module")
    return "\n".join(lines) + "\n"


def gen_broker_config(v):
    conn, net, plan = v["connection"], v["network"], v["elb_plan"]

    plans_json = json.dumps([{
        "name": plan["name"],
        "id": plan["id"],
        "description": plan["description"],
        "display_name": plan["name"],
        "l4_flavor_id": plan["l4_flavor_id"],
        "l7_flavor_id": plan["l7_flavor_id"],
    }], separators=(",", ":"))

    lines = [
        "# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that",
        "# file and run `make gen-config` instead of editing this one.",
        "#",
        "#   csb serve --config hcs-broker.yaml",
        "#",
        "# Credentials stay in the environment (HCS_ACCESS_KEY / HCS_SECRET_KEY, or",
        "# HCS_DOMAIN_NAME / HCS_USER_NAME / HCS_USER_PASSWORD).",
        "",
        "hcs:",
        f"  cloud: {conn['cloud']}",
        f"  region: {conn['region']}",
    ]
    if conn.get("auth_url"):
        lines.append(f"  auth_url: {conn['auth_url']}")
    lines.append(f"  insecure: {str(conn.get('insecure', False)).lower()}")
    lines.append("")
    lines.append("  # Site network: one shared VPC, one subnet and security group per service — all by name.")
    lines.append(f"  vpc_name: {net['vpc_name']}")
    for svc in SERVICES:
        entry = net.get(svc) or net.get(svc.replace("-", "_"))
        if entry:
            lines.append(f"  {svc.replace('-', '_')}:")
            lines.append(f"    subnet_name: {entry['subnet_name']}")
            if "security_group_name" in entry:
                lines.append(f"    security_group_name: {entry['security_group_name']}")
    lines.append("")
    lines.append("# Plans for services whose sizing values are site-specific.")
    lines.append("service:")
    lines.append("  csb-hcs-elb:")
    lines.append(f"    plans: '{plans_json}'")
    lines.append("")
    return "\n".join(lines)


def main():
    with open(VALUES_FILE) as f:
        v = yaml.safe_load(f)

    missing = [s for s in SERVICES if s not in v["instances"]]
    if missing:
        sys.exit(f"site-values.yaml is missing instances for: {', '.join(missing)}")

    config = gen_broker_config(v)
    BROKER_CONFIG.write_text(config)
    print(f"wrote {BROKER_CONFIG.relative_to(ROOT)}")

    shared = [
        "# -----------------------------------------------------------------------------",
        "# Shared values for every module — GENERATED by scripts/gen-config.py from",
        "# config/site-values.yaml; edit that file and run `make gen-config`.",
        "# Pass it FIRST so per-module files can override:",
        "#   tofu apply -var-file=examples/shared.tfvars -var-file=examples/<svc>/<mod>.tfvars",
        "# -----------------------------------------------------------------------------",
        "",
        "# --- connection ---",
        kv("region", v["connection"]["region"]),
        kv("cloud", v["connection"]["cloud"]),
        "",
        "# --- shared network ---",
        kv("vpc_name", v["network"]["vpc_name"]),
        "",
    ]
    shared_path = ROOT / "examples" / "shared.tfvars"
    shared_path.write_text("\n".join(shared))
    print(f"wrote {shared_path.relative_to(ROOT)}")

    for svc in SERVICES:
        out = ROOT / "examples" / svc / "provision.tfvars"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(gen_provision_tfvars(v, svc))
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
