# -----------------------------------------------------------------------------
# csb-hcs-csms — provision
# GENERATED by scripts/gen-config.py from config/site-values.yaml — edit that
# file and run `make gen-config` instead of editing this one.
# Run:  cd terraform/csms/provision
#       tofu init
#       tofu plan  -var-file=../../examples/shared.tfvars -var-file=../../examples/csms/provision.tfvars
#       tofu apply -var-file=../../examples/shared.tfvars -var-file=../../examples/csms/provision.tfvars
# Auth: export HCS_ACCESS_KEY=... HCS_SECRET_KEY=...   (or IAM user/password)
#       export HCS_INSECURE=true                        (self-signed certs)
# -----------------------------------------------------------------------------

# --- secret ---
secret_name = "csb-test-secret"

# --- instance ---

# secret_text = "..."                            # optional; random when omitted
# kms_key_id  = "..."                            # optional; default KMS key when omitted

# --- tags ---
labels = {}
# namespace / instance_name / created_by tags come from the broker when it runs this module
